import os, json
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN","").strip()
TELEGRAM_CHAT_IDS = json.loads(os.getenv("TELEGRAM_CHAT_IDS","{}"))
DATA_DIR = os.getenv("DATA_DIR","data")
STATE_JSON = os.getenv("STATE_JSON","/data/state.json")
INTERVAL = int(os.getenv("INTERVAL","60"))
SYNC_UPDATES_URL = os.getenv("SYNC_UPDATES_URL","").strip()
SYNC_ONCALL_URL = os.getenv("SYNC_ONCALL_URL","").strip()
SYNC_STAFF_URL = os.getenv("SYNC_STAFF_URL","").strip()
